modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "LGPL-3.0"

[[mods]]
modId = "moremcmeta_texture_plugin"
version = "${modVersion}"
displayName = "MoreMcmeta Texture Plugin"
authors = "soir20"
description = '''
Default plugin for MoreMcmeta that loads blur and clamp texture settings.
'''

[[dependencies.moremcmeta_texture_plugin]]
modId = "moremcmeta"
mandatory = true
versionRange = "[${minMoreMcmetaVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.moremcmeta_texture_plugin]]
modId = "forge"
mandatory = true
versionRange = "[${loaderVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moremcmeta_texture_plugin]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"